services:
  # Backend service
  intellibuddy-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: intellibuddy-backend
    ports:
      - "3001:3001"  # This exposes backend to localhost:3001
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - intellibuddy-network
    restart: unless-stopped

  # Frontend service
  intellibuddy-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: intellibuddy-frontend
    ports:
      - "5173:5173"
    environment:
      # Browser needs to use localhost, not Docker service name
      - VITE_API_BASE_URL=http://localhost:3001/api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - intellibuddy-backend
    networks:
      - intellibuddy-network
    restart: unless-stopped

networks:
  intellibuddy-network:
    driver: bridge